[package]
name = "pdv-dr-cafe"
version = "2.4.0"
description = "PDV Dr. Cafe desktop"
authors = ["Dr. Cafe"]
edition = "2021"

[lib]
name = "pdv_dr_cafe_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
