LangString addOrReinstall ${LANG_PORTUGUESEBR} "Adicionar/Reinstalar componentes"
LangString alreadyInstalled ${LANG_PORTUGUESEBR} "Ja instalado"
LangString alreadyInstalledLong ${LANG_PORTUGUESEBR} "${PRODUCTNAME} ${VERSION} ja esta instalado. Escolha a operacao desejada e clique em Avancar para continuar."
LangString appRunning ${LANG_PORTUGUESEBR} "{{product_name}} esta aberto. Feche o sistema e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESEBR} "{{product_name}} esta aberto.$\nClique em OK para fechar automaticamente."
LangString chooseMaintenanceOption ${LANG_PORTUGUESEBR} "Escolha a opcao de manutencao."
LangString choowHowToInstall ${LANG_PORTUGUESEBR} "Escolha como deseja instalar ${PRODUCTNAME}."
LangString createDesktop ${LANG_PORTUGUESEBR} "Criar atalho na area de trabalho"
LangString dontUninstall ${LANG_PORTUGUESEBR} "Nao desinstalar"
LangString dontUninstallDowngrade ${LANG_PORTUGUESEBR} "Nao desinstalar (nao e permitido voltar versao sem desinstalar)"
LangString failedToKillApp ${LANG_PORTUGUESEBR} "Nao foi possivel fechar {{product_name}}. Feche o sistema e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESEBR} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_PORTUGUESEBR} "Uma versao mais nova de ${PRODUCTNAME} ja esta instalada. Nao e recomendado instalar uma versao antiga. Se precisar continuar, desinstale a versao atual antes."
LangString older ${LANG_PORTUGUESEBR} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESEBR} "Uma versao $R4 de ${PRODUCTNAME} esta instalada. Para atualizacao comum, escolha Nao desinstalar e continue."
LangString silentDowngrades ${LANG_PORTUGUESEBR} "Nao e permitido voltar versao neste instalador silencioso. Use o instalador manual.$\n"
LangString unableToUninstall ${LANG_PORTUGUESEBR} "Nao foi possivel desinstalar."
LangString uninstallApp ${LANG_PORTUGUESEBR} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESEBR} "Desinstalar antes de instalar"
LangString unknown ${LANG_PORTUGUESEBR} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESEBR} "Falha ao instalar o WebView2. O sistema nao abre sem ele. Reinicie o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESEBR} "Erro ao baixar WebView2: $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESEBR} "WebView2 baixado com sucesso."
LangString webview2Downloading ${LANG_PORTUGUESEBR} "Baixando WebView2..."
LangString webview2InstallError ${LANG_PORTUGUESEBR} "Erro ao instalar WebView2. Codigo: $1"
LangString webview2InstallSuccess ${LANG_PORTUGUESEBR} "WebView2 instalado com sucesso."
LangString deleteAppData ${LANG_PORTUGUESEBR} "Apagar dados do aplicativo"
