name: Deploy to GitHub Pages

on:
  push:
    branches: ['main'] # Certifique-se de que sua branch principal se chama main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Força o uso do Node 24 para evitar avisos de obsolescência em 2026
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Otimiza o tempo de instalação

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta que o Vite gera após o build
          branch: gh-pages # Branch onde o site final será hospedado
